### ISSUE TITLE
Still freezes game

### ISSUE THREAD

**Issue by Tugoland** [Gaztoof/GMod-SDK#10]
I inject the dll into my gmod 64x with xenos 64x and it still freezes my game and I am on gmod 64 beta I freezes with anooying hev sound spamming Still not working I had to ctrl and alt delete to restart my pc cause I can't exit out there is two betas the chromium that is 64 but outdated and author 64x that is not outdated I dont know what's going on I dont know if the dll is causing the issue cause I downloaded from unkown cheats.

**Comment by uwufuckme** [comment]
dude you have to compile it yourself not download a precompiled dll from the internet.

**Comment by Gaztoof** [comment]
Just make sure your game is in chromium x64, and that you launch it in x64 mode. As simple as that.
