### ISSUE TITLE
ScriptDetour Improvement

### ISSUE THREAD

**Issue by EvaisaGiac** [Gaztoof/GMod-SDK#11]
Unless I am misunderstanding this is really bad practice.

```
std::ifstream inFile;
inFile.open(detourDir.string());
if (inFile.good() && fileName != "runString.lua") {

	std::string content((std::istreambuf_iterator<char>(inFile)),
		(std::istreambuf_iterator<char>()));
	if (!strcmp(content.c_str(), fileContent.c_str()))return {};

	fileContent = content;
	return fileContent;
}
else {
	std::ofstream outDetourFile;
	outDetourFile.open(detourDir.string());
	if (outDetourFile.good())
	{
		outDetourFile << fileContent;
		outDetourFile.close();
	}
}
```

The problem is that you are saving every server file into the detour folder, in my original code this was not the intention. 
The intention was for people to place the scripts themselves. 
The reason for this is that when you have all the scripts pre placed in the detour folder you will no longer be getting any script updates from servers because there is already a script there.
A better solution for a runtime detour would be to instead have the detour scripts that users add append onto the original script. This way you can do stuff like rerouting functions without replacing the entire file.

```
OldEpicFunction = EpicFunction
EpicFunction = function()
    -- Do your own stuff
    OldEpicFunction()
    -- Do your own stuff
end
```

Something like this would probably work?

```
std::ifstream inFile;
inFile.open(detourDir.string());
if (inFile.good() && fileName != "runString.lua") {

	std::string content((std::istreambuf_iterator<char>(inFile)),
		(std::istreambuf_iterator<char>()));
	if (!strcmp(content.c_str(), fileContent.c_str()))return {};

	fileContent = fileContent + "\n\n" + content;
	return fileContent;
}
```

**Comment by Gaztoof** [comment]
Hi, totally forgot to reply to this issue but pretty sure every issue about this has been resolved. Detouring doesn't saves any lua file anymore, only the folders for convenience purposes.
