### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by darklunny** [Gaztoof/GMod-SDK#16]
![image](https://user-images.githubusercontent.com/91416244/134805989-165ae1ad-5c32-44bf-aab8-de52757959c1.png)
help please

**Comment by daddy2365435** [comment]
![image](https://user-images.githubusercontent.com/91416244/134806070-b5004657-8c82-4f5f-bc05-751ad6f2c9c0.png)
this

**Comment by dannythehacker** [comment]
install directx sdk

**Comment by Gaztoof** [comment]
Please read the project's requirements, and always rebuild instead of building.
