### ISSUE TITLE
Screengrab issues?

### ISSUE THREAD

**Issue by sadesguy** [Gaztoof/GMod-SDK#24]
so I've joined this Russian server called "Wayzer's RP" and first of all the cheat wasn't rendering on the client side, but the feature like bhop was working fine.

```
After several hours I got banned for cheats (I had the FOV circle and the thing at the top left corner) and it was seen on the screengrab pic the admin shown me! 
```
"How strange?" I've thought, the entire cheat's UI could not be opened too! I could not fix  this by myself

**Comment by Gaztoof** [comment]
I will try to do research on this, i've noticed some server manage to break the cheat's visuals. But it shouldn't be on their screengrab tho so it's very weird.
