### ISSUE TITLE
unresolved external symbol (Memory.cpp)

### ISSUE THREAD

**Issue by vbvp** [Gaztoof/GMod-SDK#25]
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "void __cdecl RestoreVMTHook(void * * *,void *,int)" (?RestoreVMTHook@@YAXPEAPEAPEAXPEAXH@Z dllmain.obj	1	
---------------------------------------------------------------------------------------------------------------------------------------
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "char * __cdecl GetRealFromRelative(char *,int,int,bool)" (?GetRealFromRelative@@YAPEADPEADHH_N@Z)	GMod-SDK dllmain.obj	1	
----------------------------------------------------------------------------------------------------------------------------------------
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "char const * __cdecl findPattern(char const *,class std::basic_string_view<char,struct std::char_traits<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?findPattern@@YAPEBDPEBDV?$basic_string_view@DU?$char_traits@D@std@@@std@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@@Z)	GMod-SDK	dllmain.obj	1

**Comment by Gaztoof** [comment]
Make sure you rebuild the project instead of just building.
