### ISSUE TITLE
[Feature Request] Mark players with certain weapons using a different color?

### ISSUE THREAD

**Issue by aur3l14no** [Gaztoof/GMod-SDK#28]
TTT / Murder may need this feature. It involves:

1. Mark players with certain weapons using a different color.
2. Customizable weapon list. (maybe even save it to some file, idk)
3. Key to Reset markers.

**Comment by aur3l14no** [comment]
I've implemented this feature myself.

**Comment by Epik123** [comment]
> I've implemented this feature myself.

did u make a pull?
