### ISSUE TITLE
aimbot issues

### ISSUE THREAD

**Issue by lraccoon112** [Gaztoof/GMod-SDK#3]
.357  
broken with the aimbot /rarely hits shots

fas2
cw2
no nospread?

also in the configs u forgot a comma so one of them says legitconfig1

**Comment by Gaztoof** [comment]
Weirdly enough, I don't have any problems with the .357

Also, i'm still working on FAS2/CW2/TFA nospreads, should be good in a few updates/days.

And thanks for pointing that out! Fixed it
