### ISSUE TITLE
cant rebuild or build

### ISSUE THREAD

**Issue by Epik123** [Gaztoof/GMod-SDK#36]
![image](https://user-images.githubusercontent.com/85456368/153682573-7fd7ee45-b8a6-4be0-9176-2c63fb011dbf.png)
![image](https://user-images.githubusercontent.com/85456368/153682607-fc0442dc-1630-41cf-96b2-830aa747448d.png)
get these errors

**Comment by Epik123** [comment]
oh and i cant seem to connect to servers while on the beta any idea how to fix

**Comment by 1230912zdfol** [comment]
download directx sdk
