### ISSUE TITLE
Get rid of Present Pattern

### ISSUE THREAD

**Issue by Sanceilaks** [Gaztoof/GMod-SDK#4]
As I see you are addicted to the Present pattern. Why not use EndScene + _ReturnAddress() ?
More info:
https://github.com/Sanceilaks/lemi_gmod_revolution/blob/9971e7aa7f44e14c108fef99be2546cbace74170/src/render_system/render_system.cpp#L106

**Comment by Gaztoof** [comment]
I don't really have any use for the EndScene hook, so I thought it wouldn't be necessary to hook it and then only setup the Present hook...

Patterns are a pretty inefficient way of getting something tho, so maybe one day, i'll do that, but thanks for the advice :D
