### ISSUE TITLE
how do I hook cl_move?

### ISSUE THREAD

**Issue by astroux** [Gaztoof/GMod-SDK#40]
#include "../globals.hpp"

typedef void(__thiscall* FN_cl_move)(float, bool);
FN_cl_move oCLMove;

void __fastcall hkCLMove(float accumulated_extra_samples,
#ifndef _WIN64
	void*, // __fastcall does literally nothing in x64, so that's why we make it inactive
#endif
	bool bFinalTick)
{

}

Here is what I go so far but it says:
![image](https://user-images.githubusercontent.com/98244657/154682388-b1dae4a6-73fe-46d0-9d3b-a2490ba7f8b3.png)

**Comment by 1230912zdfol** [comment]
the code tag thing didn't work btw for github
