### ISSUE TITLE
[SOURCE] Auto Crouch-Jump

### ISSUE THREAD

**Issue by astroux** [Gaztoof/GMod-SDK#41]
`void CrouchJump(CUserCmd* cmd)
{
    if (Settings::Misc::crouchJump && InputSystem->IsButtonDown(KEY_SPACE) && (!(localPlayer->getFlags() & FL_ONGROUND)))
        cmd->buttons |= IN_DUCK;
}
`
Some Pasta For You :)

**Comment by shockpast** [comment]
Why is this contains in issues?
