### ISSUE TITLE
Issues compiling

### ISSUE THREAD

**Issue by WEEZOOKARP** [Gaztoof/GMod-SDK#43]
1>------ Rebuild All started: Project: GMod-SDK, Configuration: Debug x64 ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(473,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(499,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build.
1>dllmain.cpp
1>C:\Users\weezo\AppData\Local\Temp\Rar$DRa21476.25121\GMod-SDK-main\GMod-SDK\dllmain.cpp(1,10): fatal error C1083: Cannot open include file: 'Windows.h': No such file or directory
1>imgui.cpp
1>C:\Users\weezo\AppData\Local\Temp\Rar$DRa21476.25121\GMod-SDK-main\GMod-SDK\ImGui\imgui.h(42,10): fatal error C1083: Cannot open include file: 'float.h': No such file or directory
1>imgui_demo.cpp
1>C:\Users\weezo\AppData\Local\Temp\Rar$DRa21476.25121\GMod-SDK-main\GMod-SDK\ImGui\imgui.h(42,10): fatal error C1083: Cannot open include file: 'float.h': No such file or directory
1>imgui_draw.cpp
1>C:\Users\weezo\AppData\Local\Temp\Rar$DRa21476.25121\GMod-SDK-main\GMod-SDK\ImGui\imgui.h(42,10): fatal error C1083: Cannot open include file: 'float.h': No such file or directory
1>imgui_impl_dx9.cpp
1>C:\Users\weezo\AppData\Local\Temp\Rar$DRa21476.25121\GMod-SDK-main\GMod-SDK\ImGui\imgui.h(42,10): fatal error C1083: Cannot open include file: 'float.h': No such file or directory
1>imgui_impl_win32.cpp
1>C:\Users\weezo\AppData\Local\Temp\Rar$DRa21476.25121\GMod-SDK-main\GMod-SDK\ImGui\imgui.h(42,10): fatal error C1083: Cannot open include file: 'float.h': No such file or directory
1>imgui_widgets.cpp
1>C:\Users\weezo\AppData\Local\Temp\Rar$DRa21476.25121\GMod-SDK-main\GMod-SDK\ImGui\imgui.h(42,10): fatal error C1083: Cannot open include file: 'float.h': No such file or directory
1>Memory.cpp
1>C:\Users\weezo\AppData\Local\Temp\Rar$DRa21476.25121\GMod-SDK-main\GMod-SDK\Memory.h(3,10): fatal error C1083: Cannot open include file: 'Windows.h': No such file or directory
1>Memory.h
1>C:\Users\weezo\AppData\Local\Temp\Rar$DRa21476.25121\GMod-SDK-main\GMod-SDK\Memory.h(3,10): fatal error C1083: Cannot open include file: 'Windows.h': No such file or directory
1>KeyValues.cpp
1>vmatrix.h
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\xmmintrin.h(79,10): fatal error C1083: Cannot open include file: 'malloc.h': No such file or directory
1>VPanelWrapper.h
1>Generating Code...
1>Done building project "GMod-SDK.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by Starline123** [comment]
You need to have DirectX Software Development Kit.
https://www.microsoft.com/en-us/download/details.aspx?id=6812

**Comment by Gaztoof** [comment]
Install your OS's SDK using Visual Studio Installer, or set the proper path in your include environment variable.
