### ISSUE TITLE
executorfront undeclared

### ISSUE THREAD

**Issue by MorganBgH** [Gaztoof/GMod-SDK#51]
![image](https://user-images.githubusercontent.com/48845173/199013684-1c07a228-d025-453f-b32d-98192ee8d4f9.png)

![image](https://user-images.githubusercontent.com/48845173/199013713-83620c99-bfe2-49d2-a505-fdf162e81dc0.png)

**Comment by NaNonnI** [comment]
even if you fix this error they are so many more bruh.
![image](https://user-images.githubusercontent.com/42698703/199021072-b2ed3a04-fd45-4dbc-81e3-0e6694fefc94.png)

**Comment by NaNonnI** [comment]
Can't build in release, even if we recompile it.
