### ISSUE TITLE
compiling issues

### ISSUE THREAD

**Issue by Goennigoegoe** [Gaztoof/GMod-SDK#53]
when im in debug mode it works but in release mode its saying that "executorFont" doesnt exist. ive tried commenting out the ifdef _DEBUG and endif but it still doesnt work.

**Comment by Goennigoegoe** [comment]
i've tried that and it still doesnt work

**Comment by Goennigoegoe** [comment]
i just now tried it again and it doesnt work still

**Comment by Gaztoof** [comment]
Alright update your source and try recompiling, should be fixed now!
Thanks for pointing it out.

**Comment by Goennigoegoe** [comment]
Thanks it works now. Also you are really good at coding in c++.
