### ISSUE TITLE
Bhopping is broken in the new versions

### ISSUE THREAD

**Issue by bruhmoment39** [Gaztoof/GMod-SDK#56]
BHOP just completely doesn't work

**Comment by Gaztoof** [comment]
I'm aware, it's because of prediction. Didn't upload on unknowncheats a version with a "junk fix" to it yet.

**Comment by bruhmoment39** [comment]
alright good to know, is there a fix on the github download?

**Comment by Gaztoof** [comment]
Yes, recompile latest version and it should be good.
