### ISSUE TITLE
utf8 bug ;(

### ISSUE THREAD

**Issue by c0nfusecode** [Gaztoof/GMod-SDK#57]
x64 :(
how to fix? plz gaztoof help
![изображение](https://user-images.githubusercontent.com/55307836/204109722-8e4d4fe3-b481-4cd6-8b36-0159fa5d12ff.png)

**Comment by kakahost** [comment]
Same problem. I think it's some problem, like when cheat injects custom symbols (is it doing that?) or loads custom textures, maybe, maybe. Holy sh*t, he hadn't answered for big problem for about 1 month, if not more. I think he is on vacation, ir working hard at real job.

**Comment by UracosVereches** [comment]
> Same problem. I think it's some problem, like when cheat injects custom symbols (is it doing that?) or loads custom textures, maybe, maybe. Holy sh*t, he hadn't answered for big problem for about 1 month, if not more. I think he is on vacation, ir working hard at real job.

i wrote about this looooong time ago(https://github.com/Gaztoof/GMod-SDK/issues/26) and for some reason he just closed this issue without any response..

**Comment by UracosVereches** [comment]
oh nevermind, it was fixed in last commit

**Comment by Gaztoof** [comment]
Issue fixed, just recompile the cheat and it should be good.
