### ISSUE TITLE
crashing when trying to call lua functions in doEsp()

### ISSUE THREAD

**Issue by UracosVereches** [Gaztoof/GMod-SDK#58]
so i have this code to get player's usergroup
```c++
ply->PushEntity();
Lua->GetField(-1, "GetNWString");
Lua->Push(-2);

Lua->PushString("UserGroup");
Lua->Call(2, 1);
std::string usergroup = Lua->GetString(-1, 0);
Lua->Pop(2);
	
return usergroup;
```

calling it here in doEsp() causes the game to crash after seconds of playing
![image](https://user-images.githubusercontent.com/78266421/210140004-6b9e9e51-d5d4-4c3e-a3ae-701407651a95.png)

and yeah it actually works
![image](https://user-images.githubusercontent.com/78266421/210140967-0e78284e-d83d-4654-a8c7-4922bd739910.png)

is it possible to fix this?

**Comment by Gaztoof** [comment]
You can not use LUA inside the present hook.
You should do it in a game thread(because present is steam's overlay, and so it's not threadsafe), cache the data about the player, and only then use it in doEsp()
