### ISSUE TITLE
Copiling issue

### ISSUE THREAD

**Issue by kakahost** [Gaztoof/GMod-SDK#60]
![image](https://user-images.githubusercontent.com/95466263/210311759-1660dea1-a935-400b-960e-db2f132d3f0b.png)

**Comment by Gaztoof** [comment]
Get the DirectX Software Development Kit. https://www.microsoft.com/en-us/download/details.aspx?id=6812
And make sure you rebuild the project instead of simply building it.

**Comment by kakahost** [comment]
Rebuild? What?

> Get the DirectX Software Development Kit. https://www.microsoft.com/en-us/download/details.aspx?id=6812 And make sure you rebuild the project instead of simply building it.
