### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by KimiKKPR** [Gaztoof/GMod-SDK#61]
Build started...
1>------ Build started: Project: GMod-SDK, Configuration: Debug x64 ------
1>dllmain.cpp
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1006,7): warning C4244: '*=': conversion from 'float' to 'short', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1007,7): warning C4244: '*=': conversion from 'float' to 'short', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1008,7): warning C4244: '*=': conversion from 'float' to 'short', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1009,7): warning C4244: '*=': conversion from 'float' to 'short', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1026,7): warning C4244: '*=': conversion from 'float' to 'short', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1027,7): warning C4244: '*=': conversion from 'float' to 'short', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1028,7): warning C4244: '*=': conversion from 'float' to 'short', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1029,7): warning C4244: '*=': conversion from 'float' to 'short', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1046,16): warning C4244: '=': conversion from 'float' to 'short', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1047,16): warning C4244: '=': conversion from 'float' to 'short', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1048,16): warning C4244: '=': conversion from 'float' to 'short', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1049,16): warning C4244: '=': conversion from 'float' to 'short', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1156,7): warning C4244: '*=': conversion from 'float' to 'int', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1157,7): warning C4244: '*=': conversion from 'float' to 'int', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1158,7): warning C4244: '*=': conversion from 'float' to 'int', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1159,7): warning C4244: '*=': conversion from 'float' to 'int', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1176,7): warning C4244: '*=': conversion from 'float' to 'int', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1177,7): warning C4244: '*=': conversion from 'float' to 'int', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1178,7): warning C4244: '*=': conversion from 'float' to 'int', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1179,7): warning C4244: '*=': conversion from 'float' to 'int', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1196,16): warning C4244: '=': conversion from 'float' to 'int', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1197,16): warning C4244: '=': conversion from 'float' to 'int', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1198,16): warning C4244: '=': conversion from 'float' to 'int', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1199,16): warning C4244: '=': conversion from 'float' to 'int', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1947,143): warning C4244: 'argument': conversion from 'double' to 'vec_t', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1947,110): warning C4244: 'argument': conversion from 'double' to 'vec_t', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1947,47): warning C4244: 'argument': conversion from 'double' to 'vec_t', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1951,61): warning C4244: 'argument': conversion from 'double' to 'vec_t', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1951,25): warning C4244: 'argument': conversion from 'double' to 'vec_t', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1955,153): warning C4244: 'argument': conversion from 'double' to 'vec_t', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1955,120): warning C4244: 'argument': conversion from 'double' to 'vec_t', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1955,52): warning C4244: 'argument': conversion from 'double' to 'vec_t', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(2473,19): warning C4244: 'argument': conversion from 'double' to 'vec_t', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(2472,32): warning C4244: 'argument': conversion from 'double' to 'vec_t', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\globals.hpp(7,10): fatal  error C1083: Cannot open include file: 'd3dx9.h': No such file or directory
1>imgui.cpp
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\ImGui\imgui.cpp(6600,144): warning C4305: 'argument': truncation from 'double' to 'float'
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\ImGui\imgui.cpp(6601,150): warning C4305: 'argument': truncation from 'double' to 'float'
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\ImGui\imgui.cpp(7227,161): warning C4305: 'argument': truncation from 'double' to 'float'
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\ImGui\imgui.cpp(7228,161): warning C4305: 'argument': truncation from 'double' to 'float'
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\ImGui\imgui.cpp(7229,160): warning C4305: 'argument': truncation from 'double' to 'float'
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\ImGui\imgui.cpp(9734,159): warning C4305: 'argument': truncation from 'double' to 'float'
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\ImGui\imgui.cpp(9735,140): warning C4305: 'argument': truncation from 'double' to 'float'
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\ImGui\imgui.cpp(11005,139): warning C4305: 'argument': truncation from 'double' to 'float'
1>imgui_demo.cpp
1>imgui_draw.cpp
1>imgui_impl_dx9.cpp
1>imgui_impl_win32.cpp
1>imgui_widgets.cpp
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\ImGui\imgui_widgets.cpp(1051,61): warning C4305: 'argument': truncation from 'double' to 'float'
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\ImGui\imgui_widgets.cpp(2422,25): warning C4091: 'extern ': ignored on left of 'ButtonCode_t' when no variable is declared
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\ImGui\imgui_widgets.cpp(3496,97): warning C4305: 'argument': truncation from 'double' to 'float'
1>Memory.cpp
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\Memory.cpp(60,43): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>Memory.h
1>KeyValues.cpp
1>vmatrix.h
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1006,7): warning C4244: '*=': conversion from 'float' to 'short', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1007,7): warning C4244: '*=': conversion from 'float' to 'short', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1008,7): warning C4244: '*=': conversion from 'float' to 'short', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1009,7): warning C4244: '*=': conversion from 'float' to 'short', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1026,7): warning C4244: '*=': conversion from 'float' to 'short', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1027,7): warning C4244: '*=': conversion from 'float' to 'short', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1028,7): warning C4244: '*=': conversion from 'float' to 'short', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1029,7): warning C4244: '*=': conversion from 'float' to 'short', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1046,16): warning C4244: '=': conversion from 'float' to 'short', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1047,16): warning C4244: '=': conversion from 'float' to 'short', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1048,16): warning C4244: '=': conversion from 'float' to 'short', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1049,16): warning C4244: '=': conversion from 'float' to 'short', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1156,7): warning C4244: '*=': conversion from 'float' to 'int', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1157,7): warning C4244: '*=': conversion from 'float' to 'int', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1158,7): warning C4244: '*=': conversion from 'float' to 'int', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1159,7): warning C4244: '*=': conversion from 'float' to 'int', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1176,7): warning C4244: '*=': conversion from 'float' to 'int', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1177,7): warning C4244: '*=': conversion from 'float' to 'int', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1178,7): warning C4244: '*=': conversion from 'float' to 'int', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1179,7): warning C4244: '*=': conversion from 'float' to 'int', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1196,16): warning C4244: '=': conversion from 'float' to 'int', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1197,16): warning C4244: '=': conversion from 'float' to 'int', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1198,16): warning C4244: '=': conversion from 'float' to 'int', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1199,16): warning C4244: '=': conversion from 'float' to 'int', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1947,143): warning C4244: 'argument': conversion from 'double' to 'vec_t', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1947,110): warning C4244: 'argument': conversion from 'double' to 'vec_t', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1947,47): warning C4244: 'argument': conversion from 'double' to 'vec_t', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1951,61): warning C4244: 'argument': conversion from 'double' to 'vec_t', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1951,25): warning C4244: 'argument': conversion from 'double' to 'vec_t', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1955,153): warning C4244: 'argument': conversion from 'double' to 'vec_t', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1955,120): warning C4244: 'argument': conversion from 'double' to 'vec_t', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(1955,52): warning C4244: 'argument': conversion from 'double' to 'vec_t', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(2473,19): warning C4244: 'argument': conversion from 'double' to 'vec_t', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\tier0\Vector.h(2472,32): warning C4244: 'argument': conversion from 'double' to 'vec_t', possible loss of data
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\mathlib\mathlib.h(1814,19): warning C4244: 'return': conversion from 'double' to 'float', possible loss of data
1>VPanelWrapper.h
1>Generating Code...
1>Done building project "GMod-SDK.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Elapsed 00:20.302 ==========

**Comment by KimiKKPR** [comment]
1>C:\Users\proga\OneDrive\Bureau\GMod-SDK-Kimi\GMod-SDK\globals.hpp(7,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory  

how could i fix this

**Comment by maplepy** [comment]
how did you compile?
