### ISSUE TITLE
Failed to find pattern "Present"

### ISSUE THREAD

**Issue by eggooooo** [Gaztoof/GMod-SDK#81]
refer to title, cheat in its current (abandoned) state doesn't work

**Comment by krll-kov** [comment]
same

**Comment by Alex62661** [comment]
same

**Comment by mousetrapz** [comment]
I had this same issue when I downloaded the UnknownCheats version, but I just complied it myself (which is what you should really do instead, for your own security) and it worked fine.

**Comment by eggooooo** [comment]
> I had this same issue when I downloaded the UnknownCheats version, but I just complied it myself (which is what you should really do instead, for your own security) and it worked fine.

no amount of "compiling it yourself" will magically make it work in its current state.
the cheat's outdated and too far behind with all the updates that have come out since then.
