### ISSUE TITLE
Freezes game as soon as injected

### ISSUE THREAD

**Issue by Tugoland** [Gaztoof/GMod-SDK#9]
so I inject it and it quickly freezes my game and there is an white cursor and and author mouse I can move please fix this I install Microsoft visual studio 2019 c++ and game dev c++ and everything and I try injecting with author injector but when ever injecting xenos says failed to find pattern "cl_move" please contact us asap

**Comment by Gaztoof** [comment]
Please, just make sure the game is in the chromium branch, and that you launch it as x64.

Also make sure you're injecting in the right process, there's multiple gmod.exe

Closing issue.

**Comment by Tugoland** [comment]
I am already on 64 bits its still doing this I did it with also xenos 64

**Comment by Tugoland** [comment]
Is it the one that starts with the "chromium 64x-84x" or 64x-84x chroium". which beta is it @Gaztoof

**Comment by Geral3** [comment]
you good?

**Comment by Tugoland** [comment]
Is it the chromium with update behide or the x64-84 like I don't understand

**Comment by Gaztoof** [comment]
Simply inject into the right process. Usually it's the gmod.exe taking up the most ram.

The beta is named chromium x64-x86
